name = "nostr-relay-watcher"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[durable_objects.bindings]]
name = "RELAY_WATCHER"
class_name = "RelayWatcher"

[exports.RelayWatcher]
type = "durable-object"
storage = "sqlite"

[vars]
NEAR_RPC = "https://rpc.testnet.fastnear.com"
RELAY_URLS = "wss://relay.primal.net,wss://nos.lol,wss://relay.damus.io"
RELAY_URL = "wss://relay.primal.net"
NEAR_ACCOUNT_ID = "nw82a7e91.testnet"
TREASURY_CONTRACT_ID = "gov.anon372340656.testnet"
TREASURY_CONTRACT_IDS = "stuff.kampy.testnet,gov.anon372340656.testnet,govtestsub.kampy.testnet,nostrgove2e.testnet,bro.kampy.testnet"
